-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUZ0rRxK7VG5Bs5td
Qiw1uoVG0hHIA+Z/Z95OrNGW6nSgCgYIKoZIzj0DAQehRANCAAQO9whkCqyYfFKQ
AJtf/XvpviCGvbA9WPSorGh708GHNFmT8drxROTmPAjapc+7/ms1/IT2xzJgGBHh
baZXlkDI
-----END PRIVATE KEY-----